"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { ApiError, type Client, type ClientListResponse } from "@/lib/types";
import { ClientDeleteAction } from "@/components/client-delete-action";
import { PageHeader } from "@/components/page-header";

export function ClientsView() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams();
  const page = Math.max(Number(params.get("page") ?? "1") || 1, 1); const querySearch = params.get("search") ?? "";
  const [searchState, setSearchState] = useState({ querySearch, value: querySearch }); const search = searchState.querySearch === querySearch ? searchState.value : querySearch; const setSearch = (value: string) => setSearchState({ querySearch, value }); const [result, setResult] = useState<ClientListResponse | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; const timer = window.setTimeout(() => { void api.clients({ page, search: querySearch }).then((response) => { if (active) setResult(response); }).catch((cause: unknown) => { if (active) setError(cause instanceof ApiError ? cause.message : "Clients could not be loaded."); }); }, 250); return () => { active = false; window.clearTimeout(timer); }; }, [page, querySearch]);
  const navigate = (nextPage: number, nextSearch = search) => { const next = new URLSearchParams(); if (nextPage > 1) next.set("page", String(nextPage)); if (nextSearch.trim()) next.set("search", nextSearch.trim()); router.push(`${pathname}${next.toString() ? `?${next}` : ""}`); };
  const submitSearch = (event: React.FormEvent) => { event.preventDefault(); navigate(1, search); };
  return <div><PageHeader eyebrow="Client relationships" title="Clients" description="The people and companies behind your best work." /><div className="module-toolbar"><form className="search-form" onSubmit={submitSearch}><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search clients..." aria-label="Search clients" /><button type="submit">Search</button></form><Link href="/clients/new" className="primary-button compact-button">New client <span>+</span></Link></div>{error ? <div className="notice notice-warning"><strong>Couldn’t load clients</strong><span>{error}</span><button className="text-button" onClick={() => window.location.reload()}>Try again</button></div> : !result ? <div className="screen-state"><span className="spinner" />Loading clients...</div> : result.data.length === 0 ? <div className="empty-panel"><div className="empty-symbol">◇</div><h2>{querySearch ? "No clients found" : "Your client list is empty"}</h2><p>{querySearch ? "Try a different name, company, or email." : "Add your first client to start organizing the work around them."}</p>{!querySearch && <Link href="/clients/new" className="primary-button compact-button">Add first client <span>+</span></Link>}</div> : <><ClientTable clients={result.data} /><Pagination meta={result.meta} onChange={(nextPage) => navigate(nextPage)} /></>}</div>;
}

function ClientTable({ clients }: { clients: Client[] }) { return <div className="client-table-wrap"><table className="client-table"><thead><tr><th>Client</th><th>Company</th><th>Email</th><th>Phone</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{clients.map((client) => <tr key={client.id}><td><Link href={`/clients/${client.id}`} className="client-name">{client.name}</Link><span className="mobile-company">{client.company || "No company"}</span></td><td>{client.company || <span className="muted-cell">—</span>}</td><td>{client.email || <span className="muted-cell">—</span>}</td><td>{client.phone || <span className="muted-cell">—</span>}</td><td className="actions-cell"><Link href={`/clients/${client.id}`} className="table-action">View</Link><Link href={`/clients/${client.id}/edit`} className="table-action">Edit</Link><ClientDeleteAction id={client.id} compact /></td></tr>)}</tbody></table></div>; }
function Pagination({ meta, onChange }: { meta: ClientListResponse["meta"]; onChange: (page: number) => void }) { if (meta.last_page <= 1) return null; return <div className="pagination"><span>Showing page {meta.current_page} of {meta.last_page} · {meta.total} clients</span><div><button disabled={meta.current_page <= 1} onClick={() => onChange(meta.current_page - 1)}>← Previous</button><button disabled={meta.current_page >= meta.last_page} onClick={() => onChange(meta.current_page + 1)}>Next →</button></div></div>; }