"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { formatCents } from "@/lib/money";
import { ApiError, type Client, type ClientListResponse, type Project, type ProjectListResponse } from "@/lib/types";
import { PageHeader } from "@/components/page-header";
import { ProjectDeleteAction } from "@/components/project-delete-action";
import { ProjectStatusBadge } from "@/components/project-status-badge";

export function ProjectsView() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const page = Math.max(Number(params.get("page") ?? "1") || 1, 1); const querySearch = params.get("search") ?? ""; const status = params.get("status") ?? ""; const clientId = params.get("client_id") ?? "";
  const [searchState, setSearchState] = useState({ querySearch, value: querySearch }); const search = searchState.querySearch === querySearch ? searchState.value : querySearch; const setSearch = (value: string) => setSearchState({ querySearch, value }); const [result, setResult] = useState<ProjectListResponse | null>(null); const [clients, setClients] = useState<Client[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; const timer = window.setTimeout(() => { void api.projects({ page, search: querySearch, status, client_id: clientId ? Number(clientId) : undefined }).then((response) => { if (active) { setResult(response); setError(null); } }).catch((cause: unknown) => { if (active) setError(cause instanceof ApiError ? cause.message : "Projects could not be loaded."); }); }, 250); return () => { active = false; window.clearTimeout(timer); }; }, [page, querySearch, status, clientId]);
  useEffect(() => { let active = true; void api.clients({ page: 1, per_page: 50 }).then(async (first) => { const all = [...first.data]; for (let nextPage = 2; nextPage <= first.meta.last_page; nextPage += 1) { const next: ClientListResponse = await api.clients({ page: nextPage, per_page: 50 }); all.push(...next.data); } if (active) setClients(all); }).catch(() => { if (active) setClients([]); }); return () => { active = false; }; }, []);
  const navigate = (nextPage: number, nextSearch = search, nextStatus = status, nextClientId = clientId) => { const next = new URLSearchParams(); if (nextPage > 1) next.set("page", String(nextPage)); if (nextSearch.trim()) next.set("search", nextSearch.trim()); if (nextStatus) next.set("status", nextStatus); if (nextClientId) next.set("client_id", nextClientId); router.push(`${pathname}${next.toString() ? `?${next}` : ""}`); };
  const submitSearch = (event: React.FormEvent) => { event.preventDefault(); navigate(1, search); }; const hasFilters = Boolean(querySearch || status || clientId);
  return <div><PageHeader eyebrow="Work in motion" title="Projects" description="Keep the important work visible, owned, and moving." /><div className="module-toolbar project-toolbar"><form className="search-form" onSubmit={submitSearch}><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search projects..." aria-label="Search projects" /><button type="submit">Search</button></form><div className="project-filters"><select value={status} onChange={(event) => navigate(1, search, event.target.value, clientId)} aria-label="Filter by status"><option value="">All statuses</option><option value="active">Active</option><option value="completed">Completed</option><option value="on_hold">On hold</option></select><select value={clientId} onChange={(event) => navigate(1, search, status, event.target.value)} aria-label="Filter by client"><option value="">All clients</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></div><Link href="/projects/new" className="primary-button compact-button">New project <span>+</span></Link></div>{hasFilters && <button className="clear-filters" onClick={() => { setSearch(""); navigate(1, "", "", ""); }}>Clear filters</button>}{error ? <div className="notice notice-warning"><strong>Couldn’t load projects</strong><span>{error}</span><button className="text-button" onClick={() => window.location.reload()}>Try again</button></div> : !result ? <div className="screen-state"><span className="spinner" />Loading projects...</div> : result.data.length === 0 ? <div className="empty-panel"><div className="empty-symbol">◫</div><h2>{hasFilters ? "No projects found" : "Your project list is empty"}</h2><p>{hasFilters ? "Try a different search or clear the filters." : "Create your first project to give the work a clear home."}</p>{!hasFilters && <Link href="/projects/new" className="primary-button compact-button">Add first project <span>+</span></Link>}</div> : <><ProjectTable projects={result.data} /><ProjectPagination meta={result.meta} onChange={(nextPage) => navigate(nextPage)} /></>}</div>;
}

function ProjectTable({ projects }: { projects: Project[] }) { return <div className="client-table-wrap"><table className="client-table project-table"><thead><tr><th>Project</th><th>Client</th><th>Status</th><th>Dates</th><th>Budget</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{projects.map((project) => <tr key={project.id}><td><Link href={`/projects/${project.id}`} className="client-name">{project.name}</Link><span className="mobile-company">{project.client.name}</span></td><td>{project.client.name}</td><td><ProjectStatusBadge status={project.status} /></td><td>{project.start_date || project.end_date ? `${project.start_date ?? "—"} → ${project.end_date ?? "—"}` : <span className="muted-cell">No dates</span>}</td><td>{formatCents(project.budget_cents, project.currency_code)}</td><td className="actions-cell"><Link href={`/projects/${project.id}`} className="table-action">View</Link><Link href={`/projects/${project.id}/edit`} className="table-action">Edit</Link><ProjectDeleteAction id={project.id} compact /></td></tr>)}</tbody></table></div>; }
function ProjectPagination({ meta, onChange }: { meta: ProjectListResponse["meta"]; onChange: (page: number) => void }) { if (meta.last_page <= 1) return null; return <div className="pagination"><span>Showing page {meta.current_page} of {meta.last_page} · {meta.total} projects</span><div><button disabled={meta.current_page <= 1} onClick={() => onChange(meta.current_page - 1)}>← Previous</button><button disabled={meta.current_page >= meta.last_page} onClick={() => onChange(meta.current_page + 1)}>Next →</button></div></div>; }