"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { ApiError, type Project, type ProjectListResponse, type Task, type TaskListResponse } from "@/lib/types";
import { formatTaskDate, isTaskOverdue } from "@/lib/task-utils";
import { PageHeader } from "@/components/page-header";
import { TaskDeleteAction } from "@/components/task-delete-action";
import { TaskPriorityBadge } from "@/components/task-priority-badge";
import { TaskStatusBadge } from "@/components/task-status-badge";

export function TasksView() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const page = Math.max(Number(params.get("page") ?? "1") || 1, 1); const querySearch = params.get("search") ?? ""; const status = params.get("status") ?? ""; const priority = params.get("priority") ?? ""; const projectId = params.get("project_id") ?? "";
  const [searchState, setSearchState] = useState({ querySearch, value: querySearch }); const search = searchState.querySearch === querySearch ? searchState.value : querySearch; const setSearch = (value: string) => setSearchState({ querySearch, value }); const [result, setResult] = useState<TaskListResponse | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; const timer = window.setTimeout(() => { void api.tasks({ page, search: querySearch, status, priority, project_id: projectId ? Number(projectId) : undefined }).then((response) => { if (active) { setResult(response); setError(null); } }).catch((cause: unknown) => { if (active) setError(cause instanceof ApiError ? cause.message : "Tasks could not be loaded."); }); }, 250); return () => { active = false; window.clearTimeout(timer); }; }, [page, querySearch, status, priority, projectId]);
  useEffect(() => { let active = true; void api.projects({ page: 1, per_page: 50 }).then(async (first) => { const all = [...first.data]; for (let nextPage = 2; nextPage <= first.meta.last_page; nextPage += 1) { const next: ProjectListResponse = await api.projects({ page: nextPage, per_page: 50 }); all.push(...next.data); } if (active) setProjects(all); }).catch(() => { if (active) setProjects([]); }); return () => { active = false; }; }, []);
  const navigate = (nextPage: number, nextSearch = search, nextStatus = status, nextPriority = priority, nextProjectId = projectId) => { const next = new URLSearchParams(); if (nextPage > 1) next.set("page", String(nextPage)); if (nextSearch.trim()) next.set("search", nextSearch.trim()); if (nextStatus) next.set("status", nextStatus); if (nextPriority) next.set("priority", nextPriority); if (nextProjectId) next.set("project_id", nextProjectId); router.push(`${pathname}${next.toString() ? `?${next}` : ""}`); };
  const submitSearch = (event: React.FormEvent) => { event.preventDefault(); navigate(1, search); }; const hasFilters = Boolean(querySearch || status || priority || projectId);
  return <div><PageHeader eyebrow="Daily momentum" title="Tasks" description="The small steps behind the big outcomes." /><div className="module-toolbar project-toolbar"><form className="search-form" onSubmit={submitSearch}><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search tasks..." aria-label="Search tasks" /><button type="submit">Search</button></form><div className="project-filters"><select value={status} onChange={(event) => navigate(1, search, event.target.value, priority, projectId)} aria-label="Filter by status"><option value="">All statuses</option><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></select><select value={priority} onChange={(event) => navigate(1, search, status, event.target.value, projectId)} aria-label="Filter by priority"><option value="">All priorities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><select value={projectId} onChange={(event) => navigate(1, search, status, priority, event.target.value)} aria-label="Filter by project"><option value="">All projects</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></div><Link href="/tasks/new" className="primary-button compact-button">New task <span>+</span></Link></div>{hasFilters && <button className="clear-filters" onClick={() => { setSearch(""); navigate(1, "", "", "", ""); }}>Clear filters</button>}{error ? <div className="notice notice-warning"><strong>Couldn’t load tasks</strong><span>{error}</span><button className="text-button" onClick={() => window.location.reload()}>Try again</button></div> : !result ? <div className="screen-state"><span className="spinner" />Loading tasks...</div> : result.data.length === 0 ? <div className="empty-panel"><div className="empty-symbol">✓</div><h2>{hasFilters ? "No tasks found" : "Your task list is empty"}</h2><p>{hasFilters ? "Try different search terms or clear the filters." : "Create your first task to keep the work moving."}</p>{!hasFilters && <Link href="/tasks/new" className="primary-button compact-button">Add first task <span>+</span></Link>}</div> : <><TaskTable tasks={result.data} /><TaskPagination meta={result.meta} onChange={(nextPage) => navigate(nextPage)} /></>}</div>;
}

function TaskTable({ tasks }: { tasks: Task[] }) { return <div className="client-table-wrap"><table className="client-table task-table"><thead><tr><th>Task</th><th>Project</th><th>Status</th><th>Priority</th><th>Deadline</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{tasks.map((task) => { const overdue = isTaskOverdue(task.deadline, task.status); return <tr key={task.id}><td><Link href={`/tasks/${task.id}`} className="client-name">{task.title}</Link><span className="mobile-company">{task.project.name}</span></td><td><Link href={`/projects/${task.project.id}`} className="related-link">{task.project.name}</Link></td><td><TaskStatusBadge status={task.status} /></td><td><TaskPriorityBadge priority={task.priority} /></td><td className={overdue ? "overdue-text" : ""}>{overdue && <span className="overdue-mark">Overdue · </span>}{formatTaskDate(task.deadline)}</td><td className="actions-cell"><Link href={`/tasks/${task.id}`} className="table-action">View</Link><Link href={`/tasks/${task.id}/edit`} className="table-action">Edit</Link><TaskDeleteAction id={task.id} compact /></td></tr>; })}</tbody></table></div>; }
function TaskPagination({ meta, onChange }: { meta: TaskListResponse["meta"]; onChange: (page: number) => void }) { if (meta.last_page <= 1) return null; return <div className="pagination"><span>Showing page {meta.current_page} of {meta.last_page} · {meta.total} tasks</span><div><button disabled={meta.current_page <= 1} onClick={() => onChange(meta.current_page - 1)}>← Previous</button><button disabled={meta.current_page >= meta.last_page} onClick={() => onChange(meta.current_page + 1)}>Next →</button></div></div>; }