"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { ApiError, type Project, type ProjectListResponse, type Task, type TaskPayload, type TaskPriority, type TaskStatus } from "@/lib/types";

const empty = { project_id: "", title: "", description: "", deadline: "", priority: "medium" as TaskPriority, status: "todo" as TaskStatus };

export function TaskForm({ task }: { task?: Task }) {
  const router = useRouter(); const [values, setValues] = useState(() => task ? { project_id: String(task.project_id), title: task.title, description: task.description ?? "", deadline: task.deadline ?? "", priority: task.priority, status: task.status } : empty); const [projects, setProjects] = useState<Project[]>([]); const [projectLoading, setProjectLoading] = useState(true); const [projectError, setProjectError] = useState<string | null>(null); const [errors, setErrors] = useState<Record<string, string[]>>({}); const [formError, setFormError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; const load = async () => { try { const first = await api.projects({ page: 1, per_page: 50 }); const all = [...first.data]; for (let page = 2; page <= first.meta.last_page; page += 1) { const next: ProjectListResponse = await api.projects({ page, per_page: 50 }); all.push(...next.data); } if (active) setProjects(all); } catch (cause) { if (active) setProjectError(cause instanceof ApiError ? cause.message : "Projects could not be loaded."); } finally { if (active) setProjectLoading(false); } }; void load(); return () => { active = false; }; }, []);
  const update = (field: keyof typeof values, value: string) => setValues((current) => ({ ...current, [field]: value }));
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setErrors({}); setFormError(null); const payload: TaskPayload = { project_id: Number(values.project_id), title: values.title, description: values.description, deadline: values.deadline, priority: values.priority, status: values.status }; try { const unchangedProjectPayload: Partial<TaskPayload> = { ...payload }; delete unchangedProjectPayload.project_id; const response = task ? await api.updateTask(String(task.id), values.project_id === String(task.project_id) ? unchangedProjectPayload : payload) : await api.createTask(payload); router.push(`/tasks/${response.data.id}`); } catch (cause) { if (cause instanceof ApiError) { setErrors(cause.errors); setFormError(cause.status === 422 ? null : cause.message); } else setFormError("The task could not be saved. Please try again."); } finally { setSaving(false); } };
  return <form className="client-form" onSubmit={submit} noValidate><label className="client-field"><span>Project *</span><select required value={values.project_id} onChange={(event) => update("project_id", event.target.value)} disabled={projectLoading || Boolean(projectError)}><option value="">{projectLoading ? "Loading projects..." : projectError ? "Projects unavailable" : "Select a project"}</option>{task && !projects.some((project) => project.id === task.project_id) && <option value={task.project_id}>{task.project.name} (deleted)</option>}{projects.map((project) => <option key={project.id} value={project.id}>{project.name}{project.client?.name ? ` — ${project.client.name}` : ""}</option>)}</select>{errors.project_id && <small className="field-error">{errors.project_id[0]}</small>}{projectError && <small className="field-error">{projectError}</small>}</label><label className="client-field"><span>Task title *</span><input required value={values.title} onChange={(event) => update("title", event.target.value)} placeholder="What needs to get done?" />{errors.title && <small className="field-error">{errors.title[0]}</small>}</label><div className="form-grid"><label className="client-field"><span>Status *</span><select required value={values.status} onChange={(event) => update("status", event.target.value)}>{([["todo", "To do"], ["in_progress", "In progress"], ["done", "Done"]] as [TaskStatus, string][]).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>{errors.status && <small className="field-error">{errors.status[0]}</small>}</label><label className="client-field"><span>Priority *</span><select required value={values.priority} onChange={(event) => update("priority", event.target.value)}>{([["low", "Low"], ["medium", "Medium"], ["high", "High"]] as [TaskPriority, string][]).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>{errors.priority && <small className="field-error">{errors.priority[0]}</small>}</label></div><label className="client-field"><span>Deadline</span><input type="date" value={values.deadline} onChange={(event) => update("deadline", event.target.value)} />{errors.deadline && <small className="field-error">{errors.deadline[0]}</small>}</label><label className="client-field"><span>Description</span><textarea rows={5} value={values.description} onChange={(event) => update("description", event.target.value)} placeholder="Add context for this task..." />{errors.description && <small className="field-error">{errors.description[0]}</small>}</label>{formError && <div className="form-error" role="alert">{formError}</div>}<div className="form-actions"><Link href={task ? `/tasks/${task.id}` : "/tasks"} className="secondary-button">Cancel</Link><button className="primary-button form-submit" disabled={saving || projectLoading || (projects.length === 0 && !task)}>{saving ? "Saving..." : task ? "Save changes" : "Create task"}<span>→</span></button></div></form>;
}